
spring:
  application:
    name: ReactiveApp

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/spring_reactive
    username: postgres
    password: postgres

  flyway:
    user: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/spring_reactive

